## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 51](#1)
* [Exercise 52](#2)
* [Exercise 53](#3)
* [Exercise 54](#4)
* [Exercise 55](#5)
* [Exercise 56](#6)
* [Exercise 57](#7)
* [Exercise 58](#8)
* [Exercise 59](#9)
* [Exercise 60](#10)

### <a name='0'></a> Import of libraries

In [ ]:
import numpy as np

np.__version__

'1.18.4'

### <a name='1'></a> Exercise 51
Two arrays $ A $ and $ B $ are given below:

```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Concatenate these arrays as follows:

```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

__Tip:__ Use the _np.concatenate()_ function.

In [ ]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B), axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Concatenate these arrays as follows:

```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Tip:__ Use the _np.concatenate()_ function.

In [ ]:
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Exercise 52
The first array is given containing the data (_data_) and the second array containing the target class (_target_) for the given row:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```

Concatenate these arrays into one as shown below:

```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```

In [ ]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data, target), axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 53
The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one large array.

__Expected result:__
```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```
__Tip:__ Use the function _np.column_stack()_.


In [ ]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 54
The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split an array into three parts so that the first two columns formed the first array $ A1 $, four consecutive second array $ A2 $ and the last two third array $ A3 $.

__Tip:__ Use the function _np.split()_.

In [ ]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 2 6 4]
 [5 5 5 1]
 [6 6 2 3]
 [6 6 4 4]
 [0 6 1 4]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 55
The following numpy array $ A $ is given:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```

Calculate the total number of non-zero elements for this array.

__Tip:__ Use the function _np.count_nonzero()_.


In [ ]:
A = np.random.randint(low=0, high=2, size=(10, 6))

np.count_nonzero(A)

31

Calculate the total number of non-zero elements for each row in this array.

__Tip:__ Use the function _np.count_nonzero()_.

In [ ]:
np.count_nonzero(A, axis=1)

array([3, 4, 4, 2, 5, 3, 4, 2, 3, 1])

### <a name='6'></a> Exercise 56
An example numpy array $ A $ is given below:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```

Set the numpy library option to print arrays with specified precision. Set its value to 4 and print the $ A $ array.

In [ ]:
A = np.random.randn(10, 4)

np.set_printoptions(precision=4)
A

array([[-3.4365, -1.6884,  0.6523, -0.9882],
       [-0.538 ,  0.1229,  0.2184, -1.072 ],
       [-0.4456, -0.1783, -1.6461, -0.1967],
       [-0.3596,  1.8047, -0.0147,  0.9492],
       [-0.8974, -1.4852, -1.3179, -1.4868],
       [ 0.621 , -0.3806,  0.8338,  0.9452],
       [-0.0259,  1.1135,  0.7771,  0.5547],
       [-0.228 , -2.0037,  1.0577, -0.1781],
       [-0.5512,  0.2235,  1.0467,  1.1817],
       [ 0.3463,  0.3278, -1.9515, -0.9578]])

### <a name='7'></a> Exercise 57

The following numpy array $ A $ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision value to 8. Then set the appropriate numpy library option to suppress mathematical notation. Print the array $ A $.

__Expected result:__
```
array([0.0000012 , 0.00000017])
```


In [ ]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(suppress=True, precision=8)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Exercise 58
The following numpy array $ A $ is given:
```
A = np.random.randn(8, 4)
```
Remove the third column from the $ A $ array.

__Expected result:__
```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Tip:__ Use the _np.delete()_ function.


In [ ]:
A = np.random.randn(8, 4)

np.delete(A, [2], axis=1)

array([[ 0.43422906, -1.02742159, -0.59095391],
       [-0.5271181 , -1.24228399, -1.5150011 ],
       [-1.76067294,  1.92578974,  0.77499159],
       [-1.16856327,  0.24808781, -0.37047962],
       [ 0.77815835, -0.00526636, -2.08858014],
       [ 0.41175209,  0.37018955,  0.59462819],
       [-1.51963519,  0.38580083,  0.83120819],
       [ 0.24016826,  0.14801582,  1.85014684]])

### <a name='9'></a> Exercise 59

A one-dimensional array $ v $ (vector) is given:

```
v = np.array([3, 4, -2])
```
Calculate the norm of the vetor $ v $.


In [ ]:
v = np.array([3, 4, -2])

np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Exercise 60
An example $ A $ array is given below:

```
A = np.random.randint(10, size=(100, 30))
```
Set the numpy library option to print 10 edge elements. Print the array $ A $.


In [ ]:
A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems=10)
A

array([[4, 6, 6, 5, 0, 5, 7, 5, 3, 2, ..., 6, 2, 1, 9, 1, 6, 6, 5, 5, 3],
       [4, 1, 2, 8, 1, 8, 0, 8, 7, 7, ..., 9, 8, 9, 8, 3, 2, 8, 5, 1, 8],
       [7, 5, 1, 7, 8, 9, 4, 8, 6, 4, ..., 2, 7, 2, 5, 9, 8, 8, 6, 9, 2],
       [5, 6, 0, 6, 9, 5, 0, 0, 7, 8, ..., 2, 2, 1, 5, 4, 2, 1, 3, 6, 6],
       [0, 5, 0, 0, 6, 6, 4, 1, 0, 0, ..., 5, 0, 0, 4, 8, 3, 9, 8, 2, 6],
       [0, 0, 8, 6, 9, 5, 3, 4, 0, 0, ..., 4, 4, 6, 9, 0, 7, 3, 6, 3, 1],
       [7, 8, 7, 8, 9, 5, 7, 0, 1, 2, ..., 2, 7, 6, 0, 8, 7, 5, 5, 0, 2],
       [4, 0, 7, 1, 5, 9, 4, 2, 5, 1, ..., 9, 4, 7, 9, 2, 1, 6, 4, 9, 0],
       [0, 5, 6, 3, 8, 0, 4, 6, 6, 7, ..., 9, 2, 7, 1, 6, 1, 3, 2, 9, 5],
       [4, 0, 0, 6, 7, 5, 8, 5, 8, 1, ..., 4, 9, 8, 9, 3, 6, 7, 3, 5, 8],
       ...,
       [2, 0, 1, 0, 7, 6, 6, 0, 5, 5, ..., 4, 1, 6, 9, 9, 9, 8, 7, 4, 9],
       [6, 9, 2, 4, 0, 1, 0, 0, 9, 7, ..., 9, 3, 2, 4, 4, 6, 6, 9, 7, 5],
       [2, 9, 3, 0, 0, 2, 5, 3, 8, 0, ..., 6, 2, 5, 3, 5, 8, 0, 7, 7, 0],
       [4, 6, 6, 0, 1, 2, 